[project]
name = "opencode-flask-app"
version = "0.1.0"
description = "Hello World Flask app for OpenCode Testing Lab"
requires-python = ">=3.8"
dependencies = [
    "flask>=2.3.0",
]

[tool.uv]
dev-dependencies = []
